#+title: Dharmaḥ (धर्म:)

Dharmaḥ, a saṃskṛta term, and once the director of all spheres of a Bhāratīya life, now understood by few and misunderstood by many. Those who are familiar with Vedic texts feel strong emotional and pious attachment with it, and for those whom Vedic texts have become alienated, it appears a divisive factor. Beyond this attachment and aversion, let's try to understand Dharmaḥ from Vedāntic standpoint in which the term is defined.

#+BEGIN_QUOTE
Dharmaḥ comes from the root dhṛ, which means 'to support'. So, that which supports is Dharmaḥ; without which a being ceases to be being.
#+END_QUOTE

Say, you are seated now in a chair, what supports you? Chair. What supports chair? Floor. What supports floor? House. What supports house? Earth? Earth is rotating, revolving. What supports earth? Cosmic forces? Now what supports these forces? that is Dharmaḥ.

Ah! What?

Vedānta describes absolute Reality as pure Consciousness. The phenomenal world that we expeirence is superimposed on it, and experiences are mere sensory perceptions in it. So, essentially, there is no real individual but experiences individualized. Owing to Ignorance, one attaches oneself to body and deludes as individual. Since Consciousness is the only substratum of everything, it is verily the support, it is verily Dharmaḥ. That's why Dharmaḥ is one of the names of Śrī Viṣṇu in Viṣṇu Sahasranāma. Viṣṇu means that pervades all, that supports all.

Whether above declaration of Vedānta is true or not, is a matter of enquiry and we must do it. For the definition of Dharmaḥ, let's proceed with above declaration as true.

Our true Self is Consciousness itself, however, owing to identification with body, we assume different roles. Behaviorally, Dharmaḥ, then becomes multifold based on what is being supported. We live through different roles as a father, a mother, son, daughter, husband, wife, student, worker, soldier, politician, teacher, etc. so, there are Pitṛ Dharmaḥ, Rāṣṭra Dharmaḥ etc. What it essentially means, if we are performing each role in its trueness, we are adhering to Dharmaḥ. Otherwise, that function, ceases to be and we cause aDharmaḥ. For example, a student's Dharmaḥ is to study. But if he is bunking class, roaming around, passing time in entertainment, he ceases to be a student in true sense.

Things become complicated when a person is involved with multiple Dharmaḥ-s, and he actually is, which one to be prioritised and why? For example, a person in an office can take bribe to sell national secrets so that he can fund his daughter's education abroad. Here, Rāṣṭra Dharmaḥ and Pitṛ Dharmaḥ are at seemingly conflict. Narrow, lower or personal interests should always be given up for broader, higher or general interests. Why! Here lies the morality.

True identity of a being is Infinite Consciousness itself, so, there is no possibility of real happiness in anything narrow or finite. A being's journey is from lower to higher Self. No matter how beautiful a confinement is, one cannot live forever in it. Also, the idea of me and mine is attributed to ignorance, and cause of misery. Therefore, expansion of self is the source of increasing happiness, because it takes us to real Self; true definition of 'Be YourSelf'!

That's how, BhagavadGītā declares liberation:
#+BEGIN_VERSE
*सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज*

=sarvadharmānparityajya māmekaṃ śaraṇaṃ vraja=

Abandoning all forms of rites and duties, take refuge in Me (i.e. Conscious Self) alone.
#+END_VERSE

However, this remains a journey of a being from finite self to Infinite Self. It goes through work, it goes through devotion. In this journey, Dharmaḥ is the goal and is the path, and Vedānta aptly describes it as:

#+BEGIN_VERSE
*जगतः स्थिति-कारणं, प्राणिनां साक्षात्-अभ्युदय-निःश्रेयस-हेतुः यः सः धर्मः*

=Jagataḥ sthiti-kāraṇaṃ, prāṇināṃ sākṣāt-abhyudaya-niḥśreyasa-hetuḥ yaḥ saḥ dharmaḥ=

That which is the reason of the stability of the world and is the direct means to both secular and spiritual welfare of living beings, is Dharmaḥ
#+END_VERSE


=Oṃ Tat Sat=
=Oṃ Namaḥ Śivāya=

*References*
- https://eshop.chinmayamission.com/product/dharma
- https://shop.advaitaashrama.org/product/bhagavad-gita-hb-by-swami-gambhirananda/
