#+title: śrī rudrāṣṭakam (श्रीरुद्राष्टकम्)

śrī rudrāṣṭakam makes part of epic poem śrī rāmacaritamānasa composed by 16th century poet śrī gosvāmī tulsīdāsa.
rudrāṣṭakam means eight verses to rudra. Rudra (a form of śiva) is one who makes one cry! How terrible!
Ofcourse, it is terrible when ignorance gets destoryed, as all our notions of reality and attachments fall apart.
It is an earnest worship to śiva - a prayer to That Absoluteness, with a devoted and surredered heart, aspiring to take one
from duality to non-duality, from finite to Infinite, from darkness to light, from untruth to Truth, and from misery to
eternal bliss!

Below is my attempt to explore its deeper meaning. May śiva pardon my errors!

You may read full text and meaning here: https://greenmesg.org/stotras/shiva/rudrashtakam.php and
listen to its absorbing rendering here: https://youtu.be/bukN2P7WpwE?si=RUswstnS8XfMNbaM

#+BEGIN_EXAMPLE
नमामीशमीशान निर्वाणरूपं
#+END_EXAMPLE
#+BEGIN_QUOTE
=1.1 namāmīśamīśāna nirvāṇarūpaṃ=
#+END_QUOTE
#+BEGIN_VERSE
I bow to That
non-dual Auspiciousness
where duality ceases
and thereby cease
All pangs of heart
#+END_VERSE

#+BEGIN_EXAMPLE
विभुं व्यापकं ब्रह्मवेदस्वरूपम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=1.2 vibhuṃ vyāpakaṃ brahmavedasvarūpam=
#+END_QUOTE
#+BEGIN_VERSE
There is an integral way
To look at the world
One principle sporting
In all forms manifesting
Knowing That as Self
Is the end of all Knowledge
Then what is there to cling!
Let it take what it takes
Let it bring what it brings
#+END_VERSE

#+BEGIN_EXAMPLE
निजं निर्गुणं निर्विकल्पं निरीहं
#+END_EXAMPLE
#+BEGIN_QUOTE
=1.3 nijaṃ nirguṇaṃ nirvikalpaṃ nirīhaṃ=
#+END_QUOTE
#+BEGIN_VERSE
Beyond manifoldness
There, where
Even the last trace
of i being the meditator
and, You being meditated
Is dissolved
Free from all movements
and differences
There, where
All knots of heart
are resolved
#+END_VERSE

#+BEGIN_EXAMPLE
चिदाकाशमाकाशवासं भजेऽहम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=1.4 cidākāśamākāśavāsaṃ bhaje’ham=
#+END_QUOTE
#+BEGIN_VERSE
O Shambho
Afflicted by
my narrow vision
A life space
of i and my
I worship You
Seeking Oneness
In Yours all pervading
Conscious sky
#+END_VERSE

#+BEGIN_EXAMPLE
निराकारमोङ्करमूलं तुरीयं
#+END_EXAMPLE
#+BEGIN_QUOTE
=2.1 nirākāramoṅkaramūlaṃ turīyaṃ=
#+END_QUOTE
#+BEGIN_VERSE
O Shankara
Among the forms
You are formless
The root of ॐ
Auspicious home
That we seek forth
Pervading all three -
Sleep, Dream, Awake
You are Eternal fourth
#+END_VERSE

#+BEGIN_EXAMPLE
गिराज्ञानगोतीतमीशं गिरीशम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=2.2 girājñānagotītamīśaṃ girīśam=
#+END_QUOTE
#+BEGIN_VERSE
You are beyond
That words can describe
That mind can think
That intellect can reason
O blissful Shankara
Your grace is the highest peak
The best of human achievements
That we
Knowingly or unknowingly seek
#+END_VERSE

#+BEGIN_EXAMPLE
करालं महाकालकालं कृपालं
#+END_EXAMPLE
#+BEGIN_QUOTE
=2.3 karālaṃ mahākālakālaṃ kṛpālaṃ=
#+END_QUOTE
#+BEGIN_VERSE
Terrible for this
Delusion of time
Meditation on You
Cuts it asunder
O Shambhu, Compassionate!
To You
i humbly surrender
#+END_VERSE

#+BEGIN_EXAMPLE
गुणागारसंसारपारं नतोऽहम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=2.4 guṇāgārasaṃsārapāraṃ nato’ham=
#+END_QUOTE
#+BEGIN_VERSE
In this transmigratory
House of superimpositions
Repeatedly i am
Coming and going
On this wordly tree
Repeatedly i am
Climbing and falling
Help me cross, O Shankara
Your dāsa, devotedly calling
#+END_VERSE

#+BEGIN_EXAMPLE
तुषाराद्रिसंकाशगौरं गभिरं
#+END_EXAMPLE
#+BEGIN_QUOTE
=3.1 tuṣārādrisaṃkāśagauraṃ gabhiraṃ=
#+END_QUOTE
#+BEGIN_VERSE
Deeper in this moving nature
Immovable Like Himalayas
You, O Shambu,
Appear frosty white
That makes me aware
of both light and dark
You are That Conscious light
#+END_VERSE

#+BEGIN_EXAMPLE
मनोभूतकोटिप्रभाश्री शरीरम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=3.2 manobhūtakoṭiprabhāśrī śarīram=
#+END_QUOTE
#+BEGIN_VERSE
In You as substratum
Appears cosmic mind
and in it manifested
As rays projected
Millions beings
As individuals shine
#+END_VERSE

#+BEGIN_EXAMPLE
स्फुरन्मौलिकल्लोलिनी चारुगङ्गा
#+END_EXAMPLE
#+BEGIN_QUOTE
=3.3 sphuranmaulikallolinī cārugaṅgā=
#+END_QUOTE
#+BEGIN_VERSE
From Your head
The Cosmic Intellect
Surges forth, Mā Gangā
Perennial loving stream
of Knowledge
Whoever bathes in
Cleanses all sins
#+END_VERSE

#+BEGIN_EXAMPLE
लसद्भालबालेन्दु कण्ठे भुजङ्गा
#+END_EXAMPLE
#+BEGIN_QUOTE
=3.4 lasadbhālabālendu kaṇṭhe bhujaṅgā=
#+END_QUOTE
#+BEGIN_VERSE
Eternally alert
Your
Meditative effulgence
As sun via moon
In Creation expressed
Both together
The total reality
Intense activity
and Intense rest
#+END_VERSE

#+BEGIN_EXAMPLE
चलत्कुण्डलं भ्रूसुनेत्रं विशालं
#+END_EXAMPLE
#+BEGIN_QUOTE
=4.1 calatkuṇḍalaṃ bhrūsunetraṃ viśālaṃ=
#+END_QUOTE
#+BEGIN_VERSE
The worlds move
Like rings in Your ears
and, in these worlds
Yours only, are many eyes
Watching each self
Condemning praising
Fall and rise
#+END_VERSE

#+BEGIN_EXAMPLE
प्रसन्नाननं नीलकण्ठं दयालम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=4.2 prasannānanaṃ nīlakaṇṭhaṃ dayālam=
#+END_QUOTE
#+BEGIN_VERSE
We learn from You
O Shambhu
To hold bitterness of life
Venom of churning mind
Just midway
Like Your blue throat
Neither in nor out
Not giving way to hate
Keeping face smiling
and Heart Compassionate
#+END_VERSE

#+BEGIN_EXAMPLE
मृगाधीशचर्माम्बरं मुण्डमालं
#+END_EXAMPLE
#+BEGIN_QUOTE
=4.3 mṛgādhīśacarmāmbaraṃ muṇḍamālaṃ=
#+END_QUOTE
#+BEGIN_VERSE
Adorned with tiger skin
and skulls' garland
All make and break
Mere play of Your hand
In Your expression
Nothing is ever lost
In Your Being, we blossom
In You only we rest
#+END_VERSE

#+BEGIN_EXAMPLE
प्रियं शङ्करं सर्वनाथं भजामि
#+END_EXAMPLE
#+BEGIN_QUOTE
=4.4 priyaṃ śaṅkaraṃ sarvanāthaṃ bhajāmi=
#+END_QUOTE
#+BEGIN_VERSE
and, I have chased
Mortal desires
Making them my Gods
Now, I worship You,
O Shankara
A state that Is dearest
Auspiciousness itself
and, Lord of Lords
#+END_VERSE

#+BEGIN_EXAMPLE
प्रचण्डं प्रकृष्टं प्रगल्भं परेशं
#+END_EXAMPLE
#+BEGIN_QUOTE
=5.1 pracaṇḍaṃ prakṛṣṭaṃ pragalbhaṃ pareśaṃ=
#+END_QUOTE
#+BEGIN_VERSE
ofcourse, terrible You are
For all that is untrue
Eminent, Strong
The Supreme Truth is You
#+END_VERSE

#+BEGIN_EXAMPLE
अखण्डं अजं भानुकोटिप्रकाशं
#+END_EXAMPLE
#+BEGIN_QUOTE
=5.2 akhaṇḍaṃ ajaṃ bhānukoṭiprakāśaṃ=
#+END_QUOTE
#+BEGIN_VERSE
Unfragmented, unborn
Mysterious is this canvas
Where, all arts are drawn
A vast cosmic darkness
and lighted up stars
Pervading Source is You
O Shambhu
Nearest to near, and
Farthest to far
#+END_VERSE

#+BEGIN_EXAMPLE
त्र्यःशूलनिर्मूलनं शूलपाणिं
#+END_EXAMPLE
#+BEGIN_QUOTE
=5.3 tryaḥśūlanirmūlanaṃ śūlapāṇiṃ=
#+END_QUOTE
#+BEGIN_VERSE
Lethargy in actions.
Narrowness in vision.
Inability to surrender.
Afflicted by three
Spikes of nature
i resort to You
O Shankara!
of all That Is
You are the holder
and beholder
#+END_VERSE

#+BEGIN_EXAMPLE
भजेऽहं भवानीपतिं भावगम्यम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=5.4 bhaje’haṃ bhavānīpatiṃ bhāvagamyam=
#+END_QUOTE
#+BEGIN_VERSE
Like heat of fire
Like light of sun
Shakti-Shiva
Inseparable One
Nature both
External and Internal
Belong to Her
Then the path
To Oneness
Is of Love
World below or
Heaven above
#+END_VERSE

#+BEGIN_EXAMPLE
कलातीतकल्याण कल्पान्तकारी
#+END_EXAMPLE
#+BEGIN_QUOTE
=6.1 kalātītakalyāṇa kalpāntakārī=
#+END_QUOTE
#+BEGIN_VERSE
As on a potter's wheel
Like colorful pots
We all are made
In Your light only
As talking toys
We all are played
Then only Your Grace
Can lift us up
From cycles of appearing
and dropping dead
Relieving Freeing
From this delusion
Causing spinning head
#+END_VERSE

#+BEGIN_EXAMPLE
सदा सज्जनानन्ददाता पुरारी
#+END_EXAMPLE
#+BEGIN_QUOTE
=6.2 sadā sajjanānandadātā purārī=
#+END_QUOTE
#+BEGIN_VERSE
Lost in labyrinth
Spread across three cities*
Bewildered
Under māyic spell
Reality is illumined
To pure ones
In You, O Shambhu
whose hearts dwell
#+END_VERSE
#+BEGIN_QUOTE
=*Gross, subtle and causal bodies=
#+END_QUOTE

#+BEGIN_EXAMPLE
चिदानन्दसंदोह मोहापहारी
#+END_EXAMPLE
#+BEGIN_QUOTE
=6.3 cidānandasaṃdoha mohāpahārī=
#+END_QUOTE
#+BEGIN_VERSE
As a pot space
upside down
I find limitations
All around
Deluding myself
To be this clay
Grace, O Shambhu
and show me the way
Maybe a wisdom pore
In my existence
That makes me see
Infinitude, and
Total abundance
#+END_VERSE

#+BEGIN_EXAMPLE
प्रसीद प्रसीद प्रभो मन्मथारी
#+END_EXAMPLE
#+BEGIN_QUOTE
=6.4 prasīda prasīda prabho manmathārī=
#+END_QUOTE
#+BEGIN_VERSE
Tried
Gathering Knowledge
A mind holey with
Amorous desires
Made me a dry talker
From a leaky bucket
As if
Tried fetching water
Less music, more noise
Be Gracious, O Shankara
Be Gracious
Grace it with poise
#+END_VERSE

#+BEGIN_EXAMPLE
न यावद् उमानाथपादारविन्दं
भजन्तीह लोके परे वा नराणाम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=7.1-7.2 na yāvad umānāthapādāravindaṃ
bhajantīha loke pare vā narāṇām=
#+END_QUOTE
#+BEGIN_VERSE
No matter what is achieved
No matter what is done
It all becomes dust
In nature's cyclic run
An endless pursuit
of thirsts after thirst
Then Devoting to You,
O Shankara
From the reservoir of heart
That nectar of Love
We humans drink must
#+END_VERSE

#+BEGIN_EXAMPLE
न तावत्सुखं शान्ति सन्तापनाशं
प्रसीद प्रभो सर्वभूताधिवासं
#+END_EXAMPLE
#+BEGIN_QUOTE
=7.3-7.4 na tāvatsukhaṃ śānti santāpanāśaṃ
prasīda prabho sarvabhūtādhivāsaṃ=
#+END_QUOTE
#+BEGIN_VERSE
How can there be
Happiness and Peace
When i myself never at ease
At work, but unwilling
Seeing people as cunning
and environment, disturbing
Wish to go somewhere
Just not here!
Then
Be Gracious, O Shambhu
Show me
In everything and In all
It is You only, who dwell
All conflicts this ends
Whereever eyes rest
In reverence, ego bends
#+END_VERSE

#+BEGIN_EXAMPLE
न जानामि योगं जपं नैव पूजां
नतोऽहं सदा सर्वदा शम्भुतुभ्यम्
#+END_EXAMPLE
#+BEGIN_QUOTE
=8.1-8.2 na jānāmi yogaṃ japaṃ naiva pūjāṃ
nato’haṃ sadā sarvadā śambhutubhyam=
#+END_QUOTE
#+BEGIN_VERSE
I do not know
  How to chant
    With a mouth that lies
I do not know
  How to practice Yoga
    With a mind that cries
I do not know
  How to worship
    With an intellect dry
Then, to You
  I bow down to, forever Now
Be Gracious, O Shambhu
  and show me how!
#+END_VERSE

#+BEGIN_EXAMPLE
जराजन्मदुःखौघ तातप्यमानं
प्रभो पाहि आपन्नमामीश शंभो
#+END_EXAMPLE
#+BEGIN_QUOTE
=8.3-8.4 jarājanmaduḥkhaugha tātapyamānaṃ
prabho pāhi āpannamāmīśa śaṃbho=
#+END_QUOTE
#+BEGIN_VERSE
In womb of nature
Being birthed
Again and again
Bearing heat of
My egoistic acts
and old age pain
Be Gracious,
O Shambho
Free me from
Mind's addictions
Protect me, my Lord
From these afflictions
#+END_VERSE

#+BEGIN_EXAMPLE
रुद्राष्टकमिदं प्रोक्तं विप्रेण हरतोषये
ये पठन्ति नरा भक्त्या तेषां शम्भुः प्रसीदति
#+END_EXAMPLE
#+BEGIN_QUOTE
=rudrāṣṭakamidaṃ proktaṃ vipreṇa haratoṣaye
ye paṭhanti narā bhaktyā teṣāṃ śambhuḥ prasīdati=
#+END_QUOTE
#+BEGIN_VERSE
Praiseworthy eight verses
Narrated by the wise
To please Har*
Ones who read and
contemplate on its meaning
are Graced by Shambhu**
To wake up to
Auspicious non-duality
#+END_VERSE
#+BEGIN_QUOTE
=*that takes away the evil= =**Self-Existing Transcendental Reality=
#+END_QUOTE

#+BEGIN_EXAMPLE
इति श्रीगोस्वामितुलसीदासकृतं श्रीरुद्राष्टकं सम्पूर्णम् ।
#+END_EXAMPLE
#+BEGIN_QUOTE
=iti śrīgosvāmitulasīdāsakṛtaṃ śrīrudrāṣṭakaṃ sampūrṇam=

Thus ends śrī rudrāṣṭakam composed by śrī gosvāmī tulsīdāsa
#+END_QUOTE

।। ॐ गौरी शङ्कराय नमः ।।
